In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4536, 8399, 5774, 7457],
 [4536, 8399, 5774, 3877],
 [4536, 3342, 5774, 7524],
 [1154, 5044, 8583, 1322, 7388],
 [1154, 5044, 8583, 1322, 3459],
 [4083, 4536, 1979, 5774, 1397],
 [844, 8735, 1, 1322]]

In [5]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4536 8399 5774 7457]
 [   0    0    0    0 4536 8399 5774 3877]
 [   0    0    0    0 4536 3342 5774 7524]
 [   0    0    0 1154 5044 8583 1322 7388]
 [   0    0    0 1154 5044 8583 1322 3459]
 [   0    0    0 4083 4536 1979 5774 1397]
 [   0    0    0    0  844 8735    1 1322]]


In [8]:
## feature representation
dim=10

In [17]:
#model=Sequential()
#model.add(Embedding(voc_size,dim,input_length=sent_length))
#model.compile('adam','mse')

In [19]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))  # Use input_shape instead
model.compile(optimizer='adam', loss='mse')

C:\Users\venka\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [20]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step


array([[[ 1.6321432e-02,  3.3157650e-02, -2.2686347e-03, -1.0180533e-02,
          2.8793741e-02,  7.8101754e-03,  3.5039376e-02, -1.5160762e-02,
         -3.9119910e-02, -2.2843122e-02],
        [ 1.6321432e-02,  3.3157650e-02, -2.2686347e-03, -1.0180533e-02,
          2.8793741e-02,  7.8101754e-03,  3.5039376e-02, -1.5160762e-02,
         -3.9119910e-02, -2.2843122e-02],
        [ 1.6321432e-02,  3.3157650e-02, -2.2686347e-03, -1.0180533e-02,
          2.8793741e-02,  7.8101754e-03,  3.5039376e-02, -1.5160762e-02,
         -3.9119910e-02, -2.2843122e-02],
        [ 1.6321432e-02,  3.3157650e-02, -2.2686347e-03, -1.0180533e-02,
          2.8793741e-02,  7.8101754e-03,  3.5039376e-02, -1.5160762e-02,
         -3.9119910e-02, -2.2843122e-02],
        [ 4.5277085e-02,  7.3617473e-03, -2.1603299e-02,  4.4799481e-02,
         -1.9644786e-02,  9.7718351e-03,  1.5906464e-02,  3.8135536e-03,
          2.6694622e-02, -7.1599968e-03],
        [-3.9324164e-02, -4.3597758e-02, -1.5536703e-02, -4.

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 4536, 8399, 5774, 7457])

In [24]:
embedded_docs.shape

(7, 8)

In [23]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None